### ISSUE TITLE
不使用预训练

### ISSUE THREAD

**Issue by so-bright** [Shank2358/LO-Det#2]
我设置这样的时候
parser.add_argument('--weight_path', type=str, default=None,             #'weight/mobilenetv2_1.0-0c6065bc.pth',
                           help='weight file path')             #default=None

错误为
Traceback (most recent call last):
  File "/home/yc/LO-Det-main/trainR.py", line 205, in <module>
    Trainer(weight_path=opt.weight_path, resume=opt.resume, gpu_id=opt.gpu_id).train()
  File "/home/yc/LO-Det-main/trainR.py", line 115, in train
    self.__save_model_weights1(epoch, mAP)
  File "/home/yc/LO-Det-main/trainR.py", line 91, in __save_model_weights1
    best_weight = os.path.join(os.path.split(self.weight_path)[0], "best1.pt")
  File "/home/yc/anaconda3/envs/torch1.7/lib/python3.7/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Process finished with exit code 1

**Comment by Shank2358** [comment]
> 我设置这样的时候
> parser.add_argument('--weight_path', type=str, default=None, #'weight/mobilenetv2_1.0-0c6065bc.pth',
> help='weight file path') #default=None
> 
> 错误为
> Traceback (most recent call last):
> File "/home/yc/LO-Det-main/trainR.py", line 205, in
> Trainer(weight_path=opt.weight_path, resume=opt.resume, gpu_id=opt.gpu_id).train()
> File "/home/yc/LO-Det-main/trainR.py", line 115, in train
> self.__save_model_weights1(epoch, mAP)
> File "/home/yc/LO-Det-main/trainR.py", line 91, in __save_model_weights1
> best_weight = os.path.join(os.path.split(self.weight_path)[0], "best1.pt")
> File "/home/yc/anaconda3/envs/torch1.7/lib/python3.7/posixpath.py", line 107, in split
> p = os.fspath(p)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> Process finished with exit code 1

![image](https://user-images.githubusercontent.com/33946139/126730595-eedd596a-acbb-4039-8238-395f71853d51.png)
注释掉115行就行。这个是我之前调试上传版本时候加的没有用，因为这一行这个在训练一个epoch之前保存一次模型，但是现在不用预训练的话，第一次是None，所以会报错。
train一个epoch之后还有一个保存，所以前面那个注释掉不用担心，这个才是我原版用到的保存。
![image](https://user-images.githubusercontent.com/33946139/126730688-47a99649-0700-4702-a3f6-2535516e9617.png)
你试试看，如果还不行就和我说。我更新一下代码现在。

**Comment by so-bright** [comment]
你好，代码又出现了这样的错误
Traceback (most recent call last):
  File "trainR.py", line 205, in <module>
    Trainer(weight_path=opt.weight_path, resume=opt.resume, gpu_id=opt.gpu_id).train()
  File "trainR.py", line 127, in train
    p, p_d = self.model(imgs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Desktop/yc/LO-Det-main/modelR/lodet.py", line 40, in forward
    out.append(self.__head_s(x_s))
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Desktop/yc/LO-Det-main/modelR/head/dsc_head_hbb.py", line 16, in forward
    p = p.view(bs, self.__nA, 5 + self.__nC, nG, nG).permute(0, 3, 4, 1, 2)
RuntimeError: shape '[5, 3, 15, 100, 100]' is invalid for input of size 3000000

**Comment by Shank2358** [comment]
> File "/home/ubuntu/Desktop/yc/LO-Det-main/modelR/head/dsc_head_hbb.py", line 16, in forward
> p = p.view(bs, self.__nA, 5 + self.__nC, nG, nG).permute(0, 3, 4, 1, 2)
> RuntimeError: shape '[5, 3, 15, 100, 100]' is invalid for input of siz

loss没换。。。。。loss也是用的OBB的，你的数据集是旋转物体的还是普通的？我更新了一版本，你再试试看。可能可以解决一部分错误，如果还有错就和我说，我接着改

**Comment by Shank2358** [comment]
> > File "/home/ubuntu/Desktop/yc/LO-Det-main/modelR/head/dsc_head_hbb.py", line 16, in forward
> > p = p.view(bs, self.__nA, 5 + self.__nC, nG, nG).permute(0, 3, 4, 1, 2)
> > RuntimeError: shape '[5, 3, 15, 100, 100]' is invalid for input of siz
> 
> loss没换。。。。。loss也是用的OBB的，你的数据集是旋转物体的还是普通的？我更新了一版本，你再试试看。可能可以解决一部分错误，如果还有错就和我说，我接着改。对了，配置文件类别数量改了吗。然后根据这个最后一样，你的batch size=5，anchor每一层是3，类别数是10？

**Comment by so-bright** [comment]
对   数据集是水平的， 恩  loss我直接用NPMMR的就可以了吧

**Comment by Shank2358** [comment]
> 对 数据集是水平的， 恩 loss我直接用NPMMR的就可以了吧

嗯嗯对的对的，我已经更新了。然后如果还是不行，可以加我微信也可以。

**Comment by lilcosmo** [comment]
> > > File "/home/ubuntu/Desktop/yc/LO-Det-main/modelR/head/dsc_head_hbb.py", line 16, in forward
> > > p = p.view(bs, self.__nA, 5 + self.__nC, nG, nG).permute(0, 3, 4, 1, 2)
> > > RuntimeError: shape '[5, 3, 15, 100, 100]' is invalid for input of siz
> > 
> > 
> > loss没换。。。。。loss也是用的OBB的，你的数据集是旋转物体的还是普通的？我更新了一版本，你再试试看。可能可以解决一部分错误，如果还有错就和我说，我接着改。对了，配置文件类别数量改了吗。然后根据这个最后一样，你的batch size=5，anchor每一层是3，类别数是10？

您好，可以提供一下OBB的loss代码吗？因为我跑训练代码时发现
                loss, loss_iou, loss_conf, loss_cls, loss_a, loss_r, loss_s = self.criterion(p, p_d, label_sbbox, label_mbbox,
                                                  label_lbbox, sbboxes, mbboxes, lbboxes)
这句会报错：ValueError: not enough values to unpack (expected 7, got 4)
